Repository onyxjs/onyx, pull requests merged in 2019-08, with the labels that each got.

#6 chore(Wotan): Install and configure Wotan
  package.json
  packages/matchers/.fimbullinter.yaml
  packages/matchers/.wotanrc.yaml
  packages/matchers/package.json
  packages/matchers/src/expect.ts
  packages/matchers/src/toHaveLength.ts
  packages/matchers/test/expect.spec.ts
  packages/matchers/test/toThrow.spec.ts
  packages/matchers/test/tslint.json
  packages/matchers/tsconfig.json
  packages/matchers/tslint.json
  packages/mock/.fimbullinter.yaml
  packages/mock/.wotanrc.yaml
  packages/mock/package.json
  packages/mock/src/mock.ts
  packages/mock/src/spy.ts
  packages/mock/src/watch.ts
  packages/mock/test/mock.spec.ts
  packages/mock/test/spy.spec.ts
  packages/mock/test/tslint.json
  packages/mock/tsconfig.json
  packages/mock/tslint.json
  yarn.lock
Labels: enhancement, work in progress

#8 feat(core): add interface
  packages/core/src/interface.ts
  packages/core/src/runnable.ts
  packages/core/src/suite.ts
  packages/core/src/test.ts
  packages/core/test/__snapshots__/interface.spec.ts.snap
  packages/core/test/__snapshots__/suite.spec.ts.snap
  packages/core/test/__snapshots__/test.spec.ts.snap
  packages/core/test/interface.spec.ts
  packages/core/test/runnable.spec.ts
  packages/core/test/suite.spec.ts
  packages/core/test/test.spec.ts
Labels: enhancement

#1 feat(core): add a new package
  packages/core/.fimbullinter.yaml
  packages/core/.wotanrc.yaml
  packages/core/README.md
  packages/core/babel.config.js
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/interface.ts
  packages/core/src/result.ts
  packages/core/src/runnable.ts
  packages/core/src/suite.ts
  packages/core/src/test.ts
  packages/core/test/__snapshots__/interface.spec.ts.snap
  packages/core/test/__snapshots__/suite.spec.ts.snap
  packages/core/test/__snapshots__/test.spec.ts.snap
  packages/core/test/interface.spec.ts
  packages/core/test/result.spec.ts
  packages/core/test/runnable.spec.ts
  packages/core/test/suite.spec.ts
  packages/core/test/test.spec.ts
  packages/core/test/tslint.json
  packages/core/tsconfig.json
  packages/core/tslint.json
  packages/core/webpack.config.js
  packages/matchers/yarn.lock
  yarn.lock
Labels: enhancement, help wanted, work in progress
